name: "AfterShip Github Pull Request Title Check"
description: "Check Pull Request Title in a Github Action."
inputs:
  regex:
    description: "The regex for the pull request title"
    required: false
    default: "^(?:[A-Z]{3,5}-[0-9]{1,9}|refactor|Revert|docs|sentry|test|ci|build|style|release|perf).*$"
  title:
      description: "The pull request title"
      required: true
runs:
  using: composite
  steps:
      - name: Check Regex
        run: ls . && ls ../ && ls ../../ && python regex_check.py --pattern "${{ inputs.regex }}" --text "${{ inputs.title }}"
        shell: sh