name: "AfterShip OpenAPI Generator Action"
description: "Run the OpenAPI Generator CLI in a Github Action."
inputs:
  path:
    required: true
    description: 'Path for openapi generator run'
  output:
    required: true
    description: 'Output path for code generated'
  token:
    required: true
    description: 'GitHub Personal Access Token'
runs:
  using: composite
  steps:
      - id: generate code
        run: docker run --rm -v /github/workspace/${{ inputs.path }}:/input -v /github/workspace/${{ inputs.output }}:/output
        shell: bash