name: "AfterShip OpenAPI Generator Action"
description: "Run the OpenAPI Generator CLI in a Github Action."
inputs:
  path:
    required: true
    description: 'Path for openapi generator run'
  output:
    required: true
    description: 'Output path for code generated'
  token:
    required: true
    description: 'GitHub Personal Access Token'
runs:
  using: composite
  steps:
       - id: generate
         run: docker run --rm -v $(pwd)/${{ inputs.path }}:/input -v $(pwd)/${{ inputs.output }}:/output jianjungki/openapi-generator-scripts:latest
         shell: bash