name: "AfterShip OpenAPI Generator Action"
description: "Run the OpenAPI Generator CLI in a Github Action."
inputs:
  path:
    required: true
    description: 'Path for openapi generator run'
  output:
    required: true
    description: 'Output path for code generated'
  token:
    required: true
    description: 'GitHub Personal Access Token'
runs:
 
  using: "composite"
  steps:
    - run: Generate Code from OpenAPI Generator Cli
      uses: addnab/docker-run-action@v3
      with:
          image: jianjungki/openapi-generator-scripts
          options: -v ${{ inputs.path }}:/input  -v ${{ inputs.output }}:/output
