name: "Python Poetry Action"
author: "@alviezhang"
description: ""

inputs:
  poetry-version:
    description: "The Poetry version to install"
    required: true
    default: ""
  virtualenvs-create:
    description: "Create a new virtual environment if one doesn't already exist"
    required: false
    default: "true"
  virtualenvs-in-project:
    description: "Create the virtualenv inside the project’s root directory"
    required: false
    default: "false"
  install-args:
    description: "Arguments passed to get-poetry.py"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: |
        curl -sSL  https://install.python-poetry.org | POETRY_VERSION=${{ inputs.poetry-version }} python - ${{ inputs.install-args }}
        poetry_path=$HOME/.poetry/bin
        echo "$poetry_path" >> $GITHUB_PATH
        export PATH="$poetry_path:$PATH"

        poetry config virtualenvs.create ${{ inputs.virtualenvs-create }}
        poetry config virtualenvs.in-project ${{ inputs.virtualenvs-in-project }}
      shell: bash
